### ISSUE TITLE
No compatible environment found in workspace

### ISSUE THREAD

**Issue by aws0jam** [Filipsi/Packsly#30]
https://imgur.com/a/0RJrHT3

**Comment by Filipsi** [comment]
Hello there!

Thanks for the issue.

First of all, just a heads up - this is just a hobby project I do in free time and use it to distribute mod-packs between friends. So there might be bugs and unexpected behavior and mostly, lack of documentation. If you want something mature and easier to get into I would recommend [SKCraft's Launcher](https://github.com/SKCraft/Launcher) platform.

Currently we are compatible with [MultiMC](https://multimc.org/) and Minecraft Server, I haven't looked into adding other platforms yet. We also have a build server where you can get the [latest build artifacts](https://ci.appveyor.com/project/Filipsi/packsly/branch/master/artifacts).

From what I can see on the screenshot, this is expected behavior. You have launched Packsly without any configuration. When it is launched as an application, it will try to run default installation specified in `packsly.json` file that can be found in build folder. It can be also run as a CLI tool via CMD or Terminal by executing it with arguments, see `Packsly3.Cli.exe --help` for more info.

You are getting "No compatible environment found" because you need to point Packsly to a MultiMC (or Minecraft Server) folder. This can be done in several ways:
- Copying the build folder into MultiMC root directory (so it is on the same level as instances folder).
- Editing `packsly.json` and specifying absolute path in `workspace` property.
- By draging & dropping MultiMC.exe onto `Packsly3.Cli.exe`
- Or by specifying it as an argument when using CLI mode, for example:
`Packsly3.Cli.exe install https://raw.githubusercontent.com/Filipsi/Packsly/master/resources/lite-modpack.json -w "D:\Games\MultiMC"`

In order to distribute modpack using this platform, you will need to create a modpack definition file, example of a basic one can be found [here](https://github.com/Filipsi/Packsly/blob/master/resources/lite-modpack.json).
